root: true

parser: '@babel/eslint-parser'

plugins: ['prettier']

extends: ['eslint:recommended', 'react-app', 'plugin:prettier/recommended']

env:
  browser: true
  es6: true
  node: true

parserOptions:
  ecmaVersion: 'latest'
  sourceType: 'module'

globals:
  firebase: true
  sinon: true
